# based on https://github.com/HughParsonage/travis-latex-ci/blob/master/.travis.yml
language: r

sudo: true
cache:
  - packages
  - /tmp/texlive
  - /$HOME/.texlive
warnings_are_errors: false

before_install:
  - source ./travis-source/texlive.sh
  - tlmgr install ncctools algorithmicx textpos linegoal import arydshln pdfcomment datetime2 tracklang marginnote bezos scalerel
  - tlmgr update --all
  - sudo apt-get update
  - sudo apt-get install texlive-bibtex-extra
  - Rscript -e "if (!requireNamespace('knitr')) install.packages('knitr')"

install: echo Installation step #do not remove this line!

script:
  - Rscript -e "library('knitr');knitr::knit('example.rnw')"
  - pdflatex example
  - bibtex example
  - pdflatex example
  - pdflatex example
