# based on https://github.com/HughParsonage/travis-latex-ci/blob/master/.travis.yml
language: r

sudo: true
cache:
  - packages
  - /tmp/texlive
  - /$HOME/.texlive
warnings_are_errors: false

before_install:
  - source ./travis-source/texlive.sh
  - tlmgr install ncctools algorithmicx
  - tlmgr update --all
  - sudo apt-get update
  - sudo apt-get install texlive-bibtex-extra
  - Rscript -e "if (!requireNamespace('knitr')) install.packages('knitr')"

install: echo Installation step #do not remove this line!

#before_script:
    # as somehow no biber package is available for ubuntu 12.04 via apt, let's just download it directly
    # - wget "http://downloads.sourceforge.net/project/biblatex-biber/biblatex-biber/0.9.9/binaries/Linux/biber-linux_x86_64.tar.gz"
#    - wget "https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/current/binaries/Linux/biber-linux_x86_64.tar.gz"
#    - tar xzf biber-linux_x86_64.tar.gz
#    - export PATH=$PATH:$PWD
#    - tlmgr update biber

script:
  - Rscript -e "library('knitr');knitr::knit('example.rnw')"
  - pdflatex example.tex
  - bibtex example.tex
  - pdflatex example.tex
  - pdflatex example.tex

# after_success: tools/deploy.sh

# notifications:
#  email: false
